---@diagnostic disable: lowercase-global
std = "lua51"
max_line_length = false
codes = true
exclude_files = { "Libs/", ".ignored/" }

ignore = {
    "21./_",
    "212/self",
    "212/profileKey",
    "311/currentValue", -- Closure state in dropdown components
    "311/RefreshProfileDropdown", -- Used in popup dialog closures
}

globals = {
    "_",
    "BuffReminders",
    "BuffRemindersAPI",
    "BuffRemindersDB",
    "SLASH_BUFFREMINDERS1",
    "SLASH_BUFFREMINDERS2",
    "SlashCmdList",
    "StaticPopupDialogs",
}

read_globals = {
    -- WoW API
    "C_ActionBar",
    "C_AddOns",
    "C_Container",
    "C_ChallengeMode",
    "C_ClassTalents",
    "C_CreatureInfo",
    "C_EquipmentSet",
    "C_Housing",
    "C_PvP",
    "C_EncodingUtil",
    "C_Item",
    "C_Spell",
    "C_Traits",
    "C_StableInfo",
    "C_Loot",
    "C_SpellActivationOverlay",
    "C_Timer",
    "C_UnitAuras",
    "CreateFrame",
    "CreateColor",
    "EJ_GetCurrentTier",
    "EJ_GetInstanceByIndex",
    "EJ_SelectTier",
    "GetActionInfo",
    "GetFlyoutInfo",
    "GetFlyoutSlotInfo",
    "GetInstanceInfo",
    "GetInventoryItemDurability",
    "GetInventoryItemID",
    "GetInventoryItemLink",
    "GetItemInfoInstant",
    "GetItemSpell",
    "GetMaxLevelForPlayerExpansion",
    "GetPetActionInfo",
    "GetCursorPosition",
    "GetNumGroupMembers",
    "GetNumSpecializations",
    "GetUnitName",
    "UnitName",
    "UnitClass",
    "GetRealmName",
    "C_ClassColor",
    "LOCALIZED_CLASS_NAMES_MALE",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpecializationInfoByID",
    "GetLocale",
    "GetSpecializationInfoForClassID",
    "GetSpecializationRole",
    "GetShapeshiftForm",
    "GetShapeshiftFormID",
    "GetShapeshiftFormInfo",
    "GetTime",
    "GetWeaponEnchantInfo",
    "InCombatLockdown",
    "issecretvalue",
    "IsInInstance",
    "IsInGroup",
    "IsInRaid",
    "IsMounted",
    "IsResting",
    "IsMouseButtonDown",
    "IsShiftKeyDown",
    "IsSpellKnownOrOverridesKnown",
    "PlaySoundFile",
    "NUM_BAG_SLOTS",
    "ReloadUI",
    "SendChatMessage",
    "Settings",
    "SettingsPanel",
    "StaticPopup_Show",
    "time",
    "UIParent",
    "IsPlayerSpell",
    "NUM_PET_ACTION_SLOTS",
    "UnitAffectingCombat",
    "UnitCanAssist",
    "UnitClass",
    "UnitCreatureFamily",
    "UnitExists",
    "UnitGroupRolesAssigned",
    "UnitIsConnected",
    "UnitIsDead",
    "UnitIsDeadOrGhost",
    "UnitIsPlayer",
    "UnitGUID",
    "UnitInVehicle",
    "UnitIsUnit",
    "UnitIsVisible",
    "UnitLevel",
    "UnitPhaseReason",
    "UnitRace",

    "strsplit",
    "strtrim",
    "tinsert",
    "wipe",

    -- WoW Enums
    "Enum",

    -- WoW Mixins
    "Mixin",
    "CreateFromMixins",
    "CallbackRegistryMixin",

    -- WoW UI globals
    "RAID_CLASS_COLORS",
    "LOCALIZED_CLASS_NAMES_MALE",
    "ColorPickerFrame",
    "DynamicResizeButton_Resize",
    "GameTooltip",
    "GameTooltip_Hide",
    "HideUIPanel",
    "Minimap",
    "PlayerSpellsFrame",
    "PlayerSpellsUtil",
    "RegisterStateDriver",
    "STANDARD_TEXT_FONT",
    "ToggleTalentFrame",
    "UIErrorsFrame",
    "UIFrameFadeIn",
    "UISpecialFrames",
    "UnregisterStateDriver",

    -- Libraries
    "LibStub",
}
